"""角色配置数据库。新增角色时优先修改这里。"""

CHARACTERS = {
    "djh": {
        "id": "djh",
        "name": "DJH",
        "description": "The fastest player on the court.",
        "ratings": {"speed": 5, "three": 3, "dunk": 2, "defense": 3},
        "color": (70, 130, 220),
        "move_speed": 5.3,
        "jump_velocity": -14.0,
        "steal_range": 55,
        "ability_type": "dash",
        "ability_name": "Lightning Dash",
        "ability_description": "Rush forward at extreme speed.",
        "ability_cooldown": 180,
        "dash_speed": 17.0,
        "dash_duration": 11,
        "shot_charge_speed": 1.0,
        "shot_perfect_min": 0.42,
        "shot_perfect_max": 0.68,
        "shot_error_scale": 88,
        "sprite_folder": "djh",
        "frame_counts": {'idle': 6, 'run': 8, 'jump': 10, 'walk': 8, 'attack_1': 4, 'attack_2': 3, 'attack_3': 4, 'hurt': 3, 'shield': 2},
        "render_height": 132,
        "ui_accent": (53, 156, 255),
    },
    "gorilla": {
        "id": "gorilla",
        "name": "BRAX",
        "description": "A dominant force in the paint.",
        "ratings": {"speed": 2, "three": 2, "dunk": 5, "defense": 5},
        "color": (125, 90, 75),
        "move_speed": 4.2,
        "jump_velocity": -12.5,
        "steal_range": 68,
        "ability_type": "ground_slam",
        "ability_name": "Ground Slam",
        "ability_description": "Knocks nearby opponents away.",
        "ability_cooldown": 300,
        "slam_range": 115,
        "slam_horizontal_force": 13,
        "slam_vertical_force": -8,
        "shot_charge_speed": 0.85,
        "shot_perfect_min": 0.50,
        "shot_perfect_max": 0.60,
        "shot_error_scale": 118,
        "sprite_folder": "gorilla",
        "frame_counts": {'idle': 6, 'run': 8, 'jump': 12, 'walk': 8, 'attack_1': 6, 'attack_2': 4, 'attack_3': 3, 'hurt': 2, 'shield': 2},
        "render_height": 140,
        "ui_accent": (255, 128, 55),
    },
    "ninja": {
        "id": "ninja",
        "name": "KAGE",
        "description": "Move like a shadow.",
        "ratings": {"speed": 4, "three": 4, "dunk": 3, "defense": 4},
        "color": (100, 90, 180),
        "move_speed": 5.8,
        "jump_velocity": -15.0,
        "steal_range": 50,
        "ability_type": "double_jump",
        "ability_name": "Shadow Jump",
        "ability_description": "Jump one more time in mid-air.",
        "ability_cooldown": 0,
        "double_jump_velocity": -13.5,
        "shot_charge_speed": 1.25,
        "shot_perfect_min": 0.44,
        "shot_perfect_max": 0.62,
        "shot_error_scale": 100,
        "sprite_folder": "ninja",
        "frame_counts": {'idle': 6, 'run': 8, 'jump': 12, 'walk': 8, 'attack_1': 5, 'attack_2': 3, 'attack_3': 4, 'hurt': 2, 'shield': 4},
        "render_height": 136,
        "ui_accent": (167, 92, 255),
    },
    "duke": {
        "id": "duke",
        "name": "DUKE",
        "description": "Turn one playmaker into two.",
        "ratings": {"speed": 4, "three": 4, "dunk": 2, "defense": 3},
        "color": (196, 42, 58),
        "move_speed": 5.2,
        "jump_velocity": -14.2,
        "steal_range": 54,
        "ability_type": "clone",
        "ability_name": "Mirror Clone",
        "ability_description": "Create a temporary clone and pass between both bodies.",
        "ability_cooldown": 780,
        "clone_duration": 420,
        "clone_support_distance": 165,
        "shot_charge_speed": 1.08,
        "shot_perfect_min": 0.43,
        "shot_perfect_max": 0.64,
        "shot_error_scale": 94,
        # Duke 本体使用 Converted Vampire；分身使用独立的 Blood Echo 形态。
        "sprite_folder": "duke",
        "frame_counts": {'idle': 5, 'run': 8, 'jump': 7, 'walk': 8, 'attack_1': 5, 'attack_2': 3, 'attack_3': 4, 'hurt': 1, 'shield': 2},
        "clone_sprite_folder": "duke_blood_echo",
        "clone_frame_counts": {'idle': 5, 'run': 6, 'jump': 6, 'walk': 6, 'attack_1': 5, 'attack_2': 4, 'attack_3': 2, 'hurt': 2},
        "render_height": 136,
        "ui_accent": (230, 48, 68),
    },
}

CHARACTER_ORDER = ["djh", "gorilla", "ninja", "duke"]
DEFAULT_PLAYER1_CHARACTER = "djh"
DEFAULT_PLAYER2_CHARACTER = "gorilla"


def get_character(character_id):
    """返回角色配置；ID 不存在时使用 DJH。"""
    return CHARACTERS.get(character_id, CHARACTERS[DEFAULT_PLAYER1_CHARACTER])
